### ISSUE TITLE
Persistent errors about vtr-xml-utils when attempting to install python-symbiflow-v2x

### ISSUE THREAD

**Issue by MidsummerNight** [SymbiFlow/python-symbiflow-v2x#105]
![v2x-issue-blurred](https://user-images.githubusercontent.com/16112299/130796293-38dd20f4-9612-4987-ab7b-7ea9cfb6e92c.PNG)

I was trying to install this v2x tool and first cloned the repository then ran "pip install ." in v2x's directory as instructed in README. However I always end up getting the errors in the picture above stating issues with vtr-xml-utils. My system is Ubuntu 20.04 with the latest patches to date and I can sucessfully build and run _symbiflow-examples_, _symbiflow-arch-def_ and _symbiflow-prjxray_. I can also confirm that my git clone of the v2x repo is correct and I do have access to https://github.com/SymbiFlow/vtr-xml-utils so my network isn't the cause. Has anyone else encountered the same problem? Is there a way to solve this? Thanks!

EDIT: ```pip install git+https://github.com/SymbiFlow/python-symbiflow-v2x.git#egg=python-symbiflow-v2x``` also doesn't work, will get a similar warning:

```
<myusername>@<myusername>-VirtualBox:~/python-symbiflow-v2x$ pip install git+https://github.com/SymbiFlow/python-symbiflow-v2x.git#egg=python-symbiflow-v2x
Collecting python-symbiflow-v2x
  Cloning https://github.com/SymbiFlow/python-symbiflow-v2x.git to /tmp/pip-install-n5ktak56/python-symbiflow-v2x
  Running command git clone -q https://github.com/SymbiFlow/python-symbiflow-v2x.git /tmp/pip-install-n5ktak56/python-symbiflow-v2x
  WARNING: Generating metadata for package python-symbiflow-v2x produced metadata for project name v2x. Fix your #egg=python-symbiflow-v2x fragments.
Collecting lxml
  Using cached lxml-4.6.3-cp38-cp38-manylinux2014_x86_64.whl (6.8 MB)
Collecting pyjson
  Using cached pyjson-1.3.0-py3-none-any.whl (4.8 kB)
ERROR: Could not find a version that satisfies the requirement vtr-xml-utils (from v2x) (from versions: none)
ERROR: No matching distribution found for vtr-xml-utils (from v2x)
```
The only difference is that there's no mention of "```(from v2x==0.0.1)```" like the output of "```pip install .```"

**Comment by mithro** [comment]
@kgugala / @acomodi - Can you look into this issue?
