### ISSUE TITLE
Build yosys during installation

### ISSUE THREAD

**Issue by kgugala** [SymbiFlow/python-symbiflow-v2x#3]
Yosys wrapper requires yosys binary. Currently it assumes it is in the PATH. We should probably build the binary during packet installation.

If we move yosys wrapper to a separate repo, the build should be done there (#2)

**Comment by mithro** [comment]
Should we just install it from conda?

**Comment by kgugala** [comment]
I think conda installation should work fine. I'm closing this issue and #14 will track the conda work

**Comment by daveshah1** [comment]
FYI, if you want to use the Python API (which has been discussed), you'll need to build Yosys with ENABLE_PYOSYS set to 1 - it defaults to disabled to avoid portability issues.
