### ISSUE TITLE
Make sure the contents of the top level `README.md` appear in the readthedocs output

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/python-symbiflow-v2x#54]
We should make sure the contents of [the toplevel `README.md`](https://github.com/SymbiFlow/python-symbiflow-v2x/blob/master/README.md) appears in the readthedocs output without having to duplicate it all.

_Originally posted by @mithro in https://github.com/SymbiFlow/python-symbiflow-v2x/pull/46/review_comment/create_

**Comment by daniellimws** [comment]
Currently in the docs there's a link to http://symbiflow-v2x.readthedocs.io/. It is not a valid site, should I remove it?

**Comment by mithro** [comment]
@daniellimws Should be https://python-symbiflow-v2x.readthedocs.io/
